# see this link for config options:
# https://www.netlifycms.org/docs/add-to-your-site/#configuration
backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: static/images
public_folder: /images

collections:
    -   name: "blog"
        label: "Blog"
        folder: "content/blog"
        create: true
        slug: "{{ slug }}"
        fields: 
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Date", name: "date", widget: "datetime"}
            - {label: "Intro Blurb", name: "description", widget: "text"}
            - {label: "Social Image", name: "meta_image", widget: "image", required: false}
            - {label: "Body", name: "body", widget: "markdown"}
    -   name: "pages"
        label: "Pages"
        files:
            -
                file: "content/about.md"
                label: "About page"
                name: "about"
                fields:
                    -   label: Title
                        name: title
                        widget: string
                    -   label: Date
                        name: date
                        widget: datetime
            

