name = "arschles"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "Aaron's custom theme"
homepage = "https://arschles.com"
tags = []
features = []
min_version = "0.0.1"

[author]
    name = "Aaron Schlesinger"
    homepage = "https://github.com/arschles"
