name: Print Changed Files
on: push
jobs:
  print_changes:
    runs-on: ubuntu-latest
    steps:
      - id: checkout-code
        name: Checkout the code
        uses: actions/checkout@v2
      - id: get_file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          # optional target repo
          githubRepo: arschles/www
          # optional output format
          output: 'json'
      - id: print_file_additions
        run: |
          ./scripts/file_changes.sh
        env:
          FILE_CHANGES_DIR: "$HOME"
          