name: Print Changed Files
on: push
jobs:
  print_changes:
    runs-on: ubuntu-latest
    steps:
      - id: checkout-code
        name: Checkout the code
        uses: actions/checkout@v2
      - id: get_file_changes
        run: |
          git diff-tree --no-commit-id --name-only -r ${GITHUB_SHA}