name: Print Changed Files
on: push
jobs:
  print_changes:
    runs-on: ubuntu-latest
    steps:
      - id: checkout-code
        name: Checkout the code
        uses: actions/checkout@v2
      - id: get_file_changes
        run: |
          echo "Running diff for sha ${GITHUB_SHA}"
          FILES_CHANGED=$(git diff-tree --no-commit-id --name-only -r "${GITHUB_SHA}")
          NUM_FILES_CHANGED=$($FILES_CHANGED | wc -l)
          echo "$NUM_FILES_CHANGED file(s) changed"